#!/usr/bin/env bash
#fizz buzz

COUNTER=1

while [ $COUNTER -lt 101 ]
do
if [ $((COUNTER%3)) = 0 ]
then
echo "Fizz"
elif [ $((COUNTER%5)) = 0 ]
then
echo "Buzz"

elif [ $((COUNTER%15)) = 0 ]
then
    echo FizzBuzz
else
    echo "$COUNTER"
fi
(( COUNTER+=1 ))
done
