#!/usr/bin/env bash
# bad luck from China,Japan and Italy

COUNTER=1
while [ $COUNTER -lt 21 ] ; do
      if [ $COUNTER = 4 ]
      then
	echo "bad luck from China"
      elif [ $COUNTER = 9 ]
      then
      echo " bad luck from Japan"
      elif [ $COUNTER = 17 ]
      then
      echo "bad luck from Italy"
      else
      echo "$COUNTER"
      fi
      (( COUNTER+=1 ))
      done
      
