#!/usr/bin/env bash
#bad from China Japan and Italy

COUNTER=1
while [ $COUNTER -lt 24 ] ; do
case $COUNTER in
    4) echo $COUNTER
       echo "bad luck from China"  ;;
    9) echo $COUNTER
       echo "bad luck from Japan"  ;;
    17) echo $COUNTER
	echo "bad luck from Italy"  ;;
*) echo $COUNTER ;;
esac
(( COUNTER+=1 ))
done

