#!/usr/bin/env bash
# bad luck from China,Japan and Italy

COUNTER=1
while [ $COUNTER -lt 21 ]  do
    case $COUNTER in
	4) echo "bad from China" ;;
	9) echo "bad from Japan" ;;
	17) echo "bad from Italy" ;;
	*) echo $COUNTER ;;
    esac
    (( COUNTER+=1 ))
done

      
